openapi: 3.0.3
info:
  contact:
    email: support@example.com
    name: API Support
    url: https://example.com/support
  description: Api Documentation
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0
  termsOfService: urn:tos
  title: Api Documentation
  version: "1.0"
servers:
- description: Inferred Url
  url: http://localhost:8080/sware/
tags:
- description: Base Products Controller
  name: base-products-controller
paths:
  /baseProducts:
    get:
      operationId: getAllBaseProductsUsingGET
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/BaseProductsDto'
                type: array
          description: OK
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: Not Found
      summary: getAllBaseProducts
      tags:
      - base-products-controller
      x-accepts: application/json
    post:
      operationId: createBaseProductsUsingPOST
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BaseProductsDto'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BaseProductsDto'
          description: OK
        "201":
          description: Created
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: Not Found
      summary: createBaseProducts
      tags:
      - base-products-controller
      x-contentType: application/json
      x-accepts: application/json
components:
  schemas:
    BaseProductsDto:
      example:
        id: 0
        varietyName: varietyName
        barcode: barcode
        nameWarehouse: nameWarehouse
      properties:
        barcode:
          type: string
        id:
          format: int64
          type: integer
        nameWarehouse:
          type: string
        varietyName:
          type: string
      title: BaseProductsDto
      type: object

