openapi: 3.0.3
info:
  title: Api Documentation
  description: Api Documentation
  termsOfService: urn:tos
  contact:
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0
  version: 1.0
servers:
  - url: http://localhost:8080/sware/
    description: Inferred Url
tags:
  - name: base-products-controller
    description: Base Products Controller
paths:
  /baseProducts:
    get:
      tags:
        - base-products-controller
      summary: getAllBaseProducts
      operationId: getAllBaseProductsUsingGET
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: #/components/schemas/BaseProductsDto
        401:
          description: Unauthorized
        403:
          description: Forbidden
        404:
          description: Not Found
    post:
      tags:
        - base-products-controller
      summary: createBaseProducts
      operationId: createBaseProductsUsingPOST
      requestBody:
        content:
          application/json:
            schema:
              $ref: #/components/schemas/BaseProductsDto
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: #/components/schemas/BaseProductsDto
        201:
          description: Created
        401:
          description: Unauthorized
        403:
          description: Forbidden
        404:
          description: Not Found

components:
  schemas:
    BaseProductsDto:
      title: BaseProductsDto
      type: object
      properties:
        barcode:
          type: string
        id:
          type: integer
          format: int64
        nameWarehouse:
          type: string
        varietyName:
          type: string

